CREATE DATABASE onbus;
USE onbus;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
telefone VARCHAR (14),
nascimento DATE,
cpf VARCHAR(14) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL
);

CREATE TABLE motoristas (
nome VARCHAR(255) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE,
telefone VARCHAR(14) NOT NULL,
email VARCHAR (255) NOT NULL UNIQUE,
cidade VARCHAR(255) NOT NULL, 
bairro VARCHAR (255) NOT NULL,
rua VARCHAR(255) NOT NULL,
observaçoes TEXT (535)
);

CREATE TABLE linhas(
nome VARCHAR(255) NOT NULL,
inicio TIME NOT NULL,
intervalo TIME NOT NULL,
termino TIME NOT NULL,
rota TEXT (535)
);